[package]
name = "ft-sync"
version = "0.1.0"
authors = ["Deepak Angrula <deepak@fifthtry.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
gitignore = "1.0.7"
ftd = "0.1.1"
thiserror = "1"
anyhow = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"